add decomposition
lahnasti/GO_praktikum pull request #1
Opened 2024-06-24 13:18 UTC by lahnasti

Я немного запуталась в этих папках, делаю на примере прошлого вебинара. Не знаю, какие переменные или функции надо вписать, помоги, пожалуйста. Ступор уже какой-то.

5 строка - файл models.go, const AllowedStatus задать не получается. не знаю ошибка ли это моя, может слайс нельзя инициализировать константой.
10 строка - файл repository.go, нужно ли эту функцию писать? или можно обойтись одной строчкой, как и было до декомпозирования по разным папка. я просто объявила переменную с созданием мапы. Но тогда что надо в сервер передавать, если у меня этот репозиторий в мэйне инициализируется и вызывается в сервере.

server.go -
13 строка, тут и смутил меня интерфейс. Туда нужно все GET, POST, PUT, DELETE функции передать? функции notblank и валидации - они где вообще должны находиться?
49 строка , нужно получить список задач, что нужно в JSON прописать?
70-75 строки, генерирую ид, преобразую в стринг, и потом получается должна записать этот task в мапу. не знаю как прописать, если у меня создана была функция new в репозитории.

![images](https://github.com/lahnasti/GO_praktikum/assets/120308068/00a86cef-5c02-4569-909c-161b00f852da)

2024-06-24 13:32 UTC, Dorrrke commented on day04/1/internal/domain/models/models.go
> +)
Тут, как и говорил лучше объявлять константы, и тогда уже расформировать слайс
Вот два варианта:
```
const (
NewStatus = "New"
EndStatus = "End"
InProgressStatus = "In progress"
)
```

Либо есть другой метод, на мой взгляд лаконичнее, но чуть запарней
```
const (
NewStatus = iota
EndStatus
InProgressStatus
)
```
Но тут у тебя в константах будут int. И тогда нужно будет чуть поработать над тем как это обыграть, что бы и строчки выводились. Это оставлю тут на подумать, а для простоты - первый вариант

2024-06-24 14:06 UTC, Dorrrke requested changes
Вроде на вопрос все ответил, но если что то еще не понятно, можешь к вечеру ближе созвониться, и на словах повторить все, может я не правильно вопрос понял и по этому не так объяснил

2024-06-26 08:46 UTC, lahnasti commented on day04/1/cmd/main.go
![Снимок экрана 2024-06-26 в 11 44 01](https://github.com/lahnasti/GO_praktikum/assets/120308068/2bb96a2c-f394-4c43-8e91-f53f8b376560)

ошибка в терминале после запуска
добавила логгер с прошлого урока

2024-06-26 10:38 UTC, lahnasti commented on day04/1/cmd/main.go
это починила, но не знаю где статус прописать, поэтому его убрала(

2024-06-28 06:36 UTC, Dorrrke commented on day04/2/internal/server/server.go
> +	Db Repository
Думаю лучше сделать эту переменную неэкспортируемой
И вернуть метод New

2024-06-28 06:36 UTC, Dorrrke commented on day04/2/internal/repository/storage.go
> +//func (db *DBstorage) UpdateUser {
Почему не реализовала?

2024-07-02 09:01 UTC, closed without merging